name: Trigger auto deployment for iot-cloud-course-locust

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/iot-cloud-course-locust-AutoDeployTrigger-2013d0dd-1870-49b8-8783-5d8df1664ad6.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.IOTCLOUDCOURSELOCUST_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.IOTCLOUDCOURSELOCUST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.IOTCLOUDCOURSELOCUST_REGISTRY_PASSWORD }}
          containerAppName: iot-cloud-course-locust
          resourceGroup: iot-cloud-course
          imageToBuild: dmtkd/iot-cloud-course-locust:${{ github.sha }}
          dockerfilePath: Dockerfile
          targetPort: 8087

     

